FROM node:18

# Set working directory
WORKDIR /app

# Copy the application code
COPY . .

# Install Node.js dependencies
RUN npm install
RUN npm run build

# Expose the port
EXPOSE 5173

# Start the Node.js application
CMD ["npm", "run", "dev"]