version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: admin-dashboard-php
    ports:
      - 4000:4000  # Serving on port 4000, change if necessary
    volumes:
      - .:/app  # Sync project files with container
      - /app/node_modules  # Anonymous volume for node_modules to avoid conflicts
    networks:
      - application
    command: php artisan serve --host=0.0.0.0 --port=4000  # Ensure using correct port
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=admin_dashboard_boilerplate
      - DB_USERNAME=root
      - DB_PASSWORD=postgrespw

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - WATCHPACK_POLLING=true 
    container_name: admin-dashboard-frontend
    ports:
      - 5173:5173  # Vite's default port for dev server
    volumes:
      - .:/app
      - /app/node_modules  # Anonymous volume for node_modules in frontend too
    networks:
      - application
    command: npm run dev  # Running Vite development server

  db:
    image: postgres:15
    container_name: admin-pgdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data  # Persist PostgreSQL data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=admin_dashboard_boilerplate
    networks:
      - application

networks:
  application:
    driver: bridge