FROM node:20.9.0-alpine

# Set working directory
WORKDIR /app

# Copy the application code
COPY . .

# Install Node.js dependencies
RUN npm install


# Expose the port
EXPOSE 5173

# Start the Node.js application
CMD ["npm", "run", "dev"]