version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: admin-dashboard-php
    ports:
      - 4000:4000
    volumes:
      - .:/app
    networks:
      - application
    command: php artisan serve --host=0.0.0.0 --port=4000
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=admin_dashboard_boilerplate
      - DB_USERNAME=root
      - DB_PASSWORD=postgrespw

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: admin-dashboard-frontend
    ports:
      - 5173:5173
    volumes:
      - .:/app
    networks:
      - application
    command: npm run dev

  db:
    image: postgres:15
    container_name: admin-pgdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=admin_dashboard_boilerplate
    networks:
      - application

networks:
  application:
    driver: bridge
